myenum =
{
    {"ZTCG_CARD" , 0},

    {"MOB", 0},
    {"EQUIP"},
    {"ACTION"},
    {"FIELD"},
    {"CHAR"},
    {"JRBOSS"},
    {"BOSS"},

    {"TYPE_MOB", 0},
    {"TYPE_EQP"},
    {"TYPE_ACT"},
    {"TYPE_FLD"},
    {"TYPE_CHAR"},
    {"TYPE_JRB"},
    {"TYPE_BOS"},
    {"TYPE_ANYMOB"},    -- a FLAG, NOT a card-type
    {"TYPE_ANY"},       -- a FLAG, NOT a card-type
    {"LVL_ACTION"},

    {"EARTH", 0},
    {"WIND"},
    {"FIRE"},
    {"WATER"},
    {"DARK"},
    {"LIGHT"},

    {"ELEM_EARTH", 0},
    {"ELEM_WIND"},
    {"ELEM_FIRE"},
    {"ELEM_WATER"},
    {"ELEM_DARK"},
    {"ELEM_LIGHT"},
    {"ELEM_ANY"},       -- a FLAG, NOT a card-element

    -- game comparator mode
    {"LESSER", 0},
    {"GREATER"},

    -- player actor mode
    {"ANY_PLAYER", 0},
    {"ONLY_PLAYER"},
    {"ONLY_ADVSRY"},

    -- recover mode
    {"RECOVER_ANY", -1},
    {"RECOVER_MOB"},
    {"RECOVER_EQP"},
    {"RECOVER_ACT"},
    {"RECOVER_FLD"},
    {"RECOVER_TOP"},

    -- attack's source type
    {"ATKSRC_MOB", 0},
    {"ATKSRC_CHA"},
    {"ATKSRC_ACT"},
    {"ATKSRC_EQP"},
    {"ATKSRC_NIL"},

    -- attack's restrictions
    {"ATKRES_NIL", 0},
    {"ATKRES_DONT_HIT_CHAR"},
    {"ATKRES_DONT_HIT_MOBS"},
    {"ATKRES_FIXED_ON_SLOT"},
    {"ATKRES_FIXED_DAMAGE"},

    -- target slot
    {"SLOT_CHAR", 0},
    {"SLOT_MOB1"},
    {"SLOT_MOB2"},
    {"SLOT_MOB3"},
    {"SLOT_MOB4"},
    {"SLOT_MOB5"},
    {"SLOT_MOB6"},
    {"SLOT_MOB7"},

    -- prevent / counter
    {"NO_EFFECT", 0},
    {"PREVENT_ATTACK"},
    {"COUNTER_ATTACK", 1},

    -- focus mobs/char - Global Attacks
    {"GLOBAL_HITCHAR", 0},
    {"GLOBAL_HITMOBS"},

    -- peek card list
    {"CARDLIST_HIDE", 0},
    {"CARDLIST_PEEK"},

    -- deck orientation - top/bottom
    {"DECK_TOP", 0},
    {"DECK_BOTTOM"},

    -- move cards from a deck to another
    {"TAKE_BYNAME", 0},
    {"TAKE_CARDID"},
    {"TAKE_NEXT"},
    {"PUT_TOP"},
    {"PUT_BOTTOM"},

    -- play card effects
    {"PLAY_NORMALSUMMON", 0},
    {"PLAY_SCOUTSUMMON"},
    {"PLAY_FORCESUMMON"},

    {"PLAY_NORMALEQUIP", 0},
    {"PLAY_GEARUPEQUIP"},

    {"PLAY_NORMALFIELD", 0},
    {"PLAY_FIRSTCARDFIELD"},    --NOTE: this only plays a field if the first card of the hand is a FIELD-type.

    --
    {"GLOBALAURA_PASS_PLAYER", 1},
    {"GLOBALAURA_PASS_ADVSRY"},
    {"GLOBALAURA_BOTH_PLAYERS"},

    -- deck type
    {"DECK_HAND", 0},
    {"DECK_DECK"},
    {"DECK_GRAV"},
    {"DECK_CARD"},

    -- table slot
    {"SLOT_PLAYERCHAR", 0},
    {"SLOT_PLAYERMOB1"},
    {"SLOT_PLAYERMOB2"},
    {"SLOT_PLAYERMOB3"},
    {"SLOT_PLAYERMOB4"},
    {"SLOT_PLAYERMOB5"},
    {"SLOT_PLAYERMOB6"},
    {"SLOT_PLAYERMOB7"},
    {"SLOT_PLAYEREQP1"},
    {"SLOT_PLAYEREQP2"},
    {"SLOT_PLAYEREQP3"},
    {"SLOT_PLAYEREQP4"},
    {"SLOT_PLAYEREQP5"},
    {"SLOT_PLAYEREQP6"},
    {"SLOT_PLAYEREQP7"},
    {"SLOT_PLAYERFLD"},
    {"SLOT_ADVSRYCHAR"},
    {"SLOT_ADVSRYMOB1"},
    {"SLOT_ADVSRYMOB2"},
    {"SLOT_ADVSRYMOB3"},
    {"SLOT_ADVSRYMOB4"},
    {"SLOT_ADVSRYMOB5"},
    {"SLOT_ADVSRYMOB6"},
    {"SLOT_ADVSRYMOB7"},
    {"SLOT_ADVSRYEQP1"},
    {"SLOT_ADVSRYEQP2"},
    {"SLOT_ADVSRYEQP3"},
    {"SLOT_ADVSRYEQP4"},
    {"SLOT_ADVSRYEQP5"},
    {"SLOT_ADVSRYEQP6"},
    {"SLOT_ADVSRYEQP7"},
    {"SLOT_ADVSRYFLD"},

    -- ZTCG card ids --
    {"LINK", 1},
    {"GREAT_DEKUS_BLESS"},
    {"GOHMA"},
    {"GORON_TUNIC"},
    {"DARK_LINK"},
    {"DESERT_COLOSSUS"},
    {"LIKELIKE"},
    {"IMPA"},
    {"TWINROVA"},
    {"PIERRE"},
    {"BLUE_POTION"},
    {"FLARE_DANCER"},
    {"ADULT_WALLET"},
    {"GORON_BRACELET"},
    {"KOKIRI_FOREST"},
    {"GOLDEN_SCALE"},
    {"MASTER_SWORD"},
    {"GERUDO_GUARD"},
    {"BOMBCHU"},
    {"PRINCESS_ZELDA"},
    {"LIZALFOS"},
    {"HOOKSHOT"},
    {"YOUNG_LINK"},
    {"GANON"},
    {"SPIRIT_MEDALLION"},
    {"GORON_RUBY"},
    {"BONGOBONGO"},
    {"GUAY"},
    {"MOBLIN"},
    {"BAZAAR_SELLER"},
    {"KING_ZORA"},
    {"NABOORU"},
    {"ANUBIS"},
    {"DEAD_HAND"},
    {"DEATH_MT_CRATER"},
    {"HYRULE_CASTLE"},
    {"LAKE_HYLIA"},
    {"RAURU"},
    {"PHANTOM_GANON"},
    {"BIGOCTO"},
    {"TAILPASARAN"},
    {"GERUDO_FORTRESS"},
    {"CURSED_VILLAGER"},
    {"POE_SISTERS"},
    {"HYLIAN_SHIELD"},
    {"DEKU_SEEDS_BAG"},
    {"BLESS_OF_TRIFORCE"},
    {"SKULLTULAS_AMBUSH"},
    {"HEART_PIECE"},
    {"MILK_BOTTLE"},
    {"STINGER"},
    {"ZORAS_SAPPHIRE"},
    {"PEAHAT"},
    {"GOLD_SKULLTULA"},
    {"LARVA_GOHMA"},
    {"MAGIC_BEANS"},
    {"SMALL_KEY"},
    {"GREAT_DEKU_TREES_KNOWLEDGE"},
    {"BOMB_RAIN"},
    {"KAKARIKO_GRAVEYARD"},
    {"MIDO"},
    {"CUCCO_LADY"},
    {"FAIRYS_AID"},
    {"TRIPLE_SHOT"},
    {"DEKU_NUT"},
    {"DARK_PATHWAY"},
    {"MAGIC_JAR"},
    {"GIVE_AWAY"},
    {"ICE_ARROW"},
    {"PLAY_OCARINA"},
    {"OPEN_CHEST"},
    {"CRYSTAL_SWITCH"},
    {"RAZE"},
    {"DINS_FIRE"},
    {"MOUNTAIN_CLIMBING"},
    {"HORSE_RIDING"},
    {"_1_TON_ROCK_LIFTING"},
    {"OCTOROK"},
    {"JOELLE"},
    {"TORCH_SLUG"},
    {"SPIKE"},
    {"BOMB_BAG"},
    {"FAIRY_SLINGSHOT"},
    {"COMPASS"},
    {"GUILLOTINE"},
    {"SKULLWALLTULA"},
    {"BABY_DODONGO"},
    {"FABULOUS_FIVE_FROGGISH_TENORS"},
    {"LEEVER"},
    {"RED_TEKTITE"},
    {"BLUE_TEKTITE"},
    {"GRANNY"},
    {"WOLFOS"},
    {"SHABOM"},
    {"SILVER_GAUNTLETS"},
    {"WORLDS_FINEST_EYE_DROPS"},
    {"OCARINA_OF_TIME"},
    {"GOSSIP_STONE"},
    {"GANONS_CASTLE"},
    {"DUNGEON_MAP"},
    {"GERUDOS_MEMBERSHIP_CARD"},
    {"SHADOW_MERGE"},
    {"GOLDEN_GAUNTLETS"},
    {"MASK_OF_TRUTH"},
    {"WARP"},
    {"GIANT_LEEVER"},
    {"BIG_POE"},
    {"SKULL_MASK"},
    {"GANONDORF"},
    {"CHEST"},
    {"SKULL_KID"},
    {"PRINCESS_RUTO"},
    {"LIGHT_MEDALLION"},
    {"FIRE_ARROW"},
    {"JUMP_QUEST_WATER"},
    {"IRON_BOOTS"},
    {"MIRROR_SHIELD"},
    {"WHITE_WOLFOS"},
    {"WHIRLING_SCYTHES"},
    {"DARUNIA"},
    {"SUNSET"},
    {"CHANNELED_STRIKE"},
    {"PURPLE_RUPEE"},
    {"REDEAD"},
    {"BEAMOS"},
    {"IRON_KNUCKLES"},
    {"DODONGO"},
    {"FREEZARD"},
    {"BUSINESS_SCRUB"},
    {"JUMP_QUEST_WIND"},
    {"UNDERGROUND_SHELTER"},
    {"HOVER_BOOTS"},
    {"EPONA"},
    {"CLAIM_CHECK"},
    {"PURPLE_POE_REMNANT"},
    {"GREEN_POE_REMNANT"},
    {"FIRE_TEMPLE"},
    {"BIGGER_BOMB_BAG"},
    {"BOMB"},
    {"MALON"},
    {"BOOMERANG"},
    {"TRICKY_SHOT"},
    {"KOKIRI_TUNIC"},
    {"STALFOS"},
    {"BIG_DEKU_BABA"},
    {"FAIRY_FOUNTAIN"},
    {"MYSTIC_SPELL"},
    {"GREAT_FAIRYS_BLESS"},
    {"KEESE"},
    {"FAIRY_BOW"},
    {"GIANTS_KNIFE"},
    {"BARI"},
    {"BIRI"},
    {"PARASITIC_TENTACLE"},
    {"GIANT_STALCHILD"},
    {"DEKU_SHIELD"},
    {"ARMOS_STATUE"},
    {"SKULLTULA"},
    {"JUMP_QUEST_FIRE"},
    {"HOOKSHOT_CLIMBING"},
    {"VOLCANIC_OVERHEAT"},
    {"ICE_CAVERN"},
    {"VOLVAGIA"},
    {"DIMENSIONAL_RIFT"},
    {"CONCEAL"},
    {"LIGHT_ARROW"},
    {"MEGATON_HAMMER"},
    {"LAKE_SCIENTIST"},
    {"KOKIRI_SWORD"},
    {"POACHERS_SAW"},
    {"BIOELETRIC_CUBE"},
    {"ZORAS_FOUNTAIN"},
    {"ZORA_TUNIC"},
    {"GIANT_QUIVER"},
    {"FLYING_CARPET"},
    {"GORON"},
    {"CLUB_MOBLIN"},
    {"ICE_KEESE"},
    {"FIRE_KEESE"},
    {"WALLMASTER"},
    {"MAD_SCRUB"},
    {"BIGGORONS_SWORD"},
    {"HYRULE_FIELD"},
    {"BARINADE"},
    {"CUCCO"},
    {"POE"},
    {"TIME_WARP"},
    {"JUMP_QUEST_DARK"},
    {"FERRY_TO_THE_OTHER_WORLD"},
    {"SHELL_BLADE"},
    {"DINOLFOS"},
    {"KING_DODONGO"},
    {"MORPHA"},
    {"BIG_GUAY"},
    {"TEMPLE_OF_TIME"},
    {"DEKU_STICK"},
    {"MARKSMANSHIP"},
    {"POE_COLLECTOR"},
    {"STALCHILD"},
    {"SHEIK"},

    {"ZTCG_UNDEFINED" , -1}
}
